apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: flask-tutorial
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-tutorial
spec:
  selector:
    matchLabels:
      app: flask-tutorial
  replicas: 4
  template:
    metadata:
      labels:
        app: flask-tutorial
    spec:
      containers:
      - name: flask-tutorial-container
        image: ankansah/flask-tutorial:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
