apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-deployment
  labels:
    app: testapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: kind-cluster-control-plane
        image: ankansah/testapi
        ports:
        - containerPort: 80
